name: Løsningsorientert
favicon: null
layout_spectrum: 0.8252795320004225
typography_spectrum: 0.36343
title: IT Solutions for the Printing Industry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#415ba8'
    - '#8dc63f'
    - '#dfe2ec'
    - '#9ca5c4'
  brandStrength: 0.7131587453186512
  lightness: 0.3034834039863199
  saturation: 0.9776617139577866
  rhythmicContrast: 0.3137061900924891
purpose: []
